[package]
name = "alloy"
version = "0.1.0"
authors = ["Leo Balduf <leobalduf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version="^1.0.104",features=["derive"]}
http = "^0.2"
failure = "^0.1"