use crate::config::InputValue;
use serde::{Deserialize, Serialize};
use std::time::Duration;

#[derive(Serialize, Deserialize, Debug, Clone, Ord, PartialOrd, PartialEq, Eq)]
#[serde(tag = "type")]
pub enum ButtonEvent {
    /// The button was pressed.
    Down,

    /// The button was depressed.
    Up,

    /// The button was pressed and released.
    /// The duration indicates for how long the button was pressed.
    Clicked { duration: Duration },

    /// An event that is generated at one-second intervals after a button was initially pressed.
    LongPress { seconds: u64 },
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct AddressedEvent {
    pub address: u16,
    pub event: Event,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Event {
    /// The time at which the event was generated, on the generating machine.
    pub timestamp: chrono::DateTime<chrono::Utc>,

    /// The actual event.
    pub inner: Result<EventKind, String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum EventKind {
    /// An event generated by buttons and other binary input devices.
    Button(ButtonEvent),

    /// A newly read or written value.
    Update { new_value: InputValue },
}

/// A timestamped input value.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimestampedInputValue {
    pub ts: chrono::DateTime<chrono::Utc>,
    pub value: Result<InputValue, String>,
}

#[derive(Serialize, Deserialize, Debug, Clone, Ord, PartialOrd, PartialEq, Eq)]
pub struct EventFilter {
    pub strategy: EventFilterStrategy,
    pub entries: Vec<EventFilterEntry>,
}

impl EventFilter {
    fn match_inner(entry: &EventFilterEntry, e: &Event) -> bool {
        match entry {
            EventFilterEntry::Any => true,
            EventFilterEntry::Kind { kind } => match &e.inner {
                Ok(inner) => match kind {
                    EventFilterKind::Update => match inner {
                        EventKind::Update { .. } => true,
                        _ => false,
                    },
                    EventFilterKind::Button { filter } => match inner {
                        EventKind::Button(e) => match filter {
                            ButtonEventFilter::Down => match e {
                                ButtonEvent::Down => true,
                                _ => false,
                            },
                            ButtonEventFilter::Up => match e {
                                ButtonEvent::Up => true,
                                _ => false,
                            },
                            ButtonEventFilter::Clicked => match e {
                                ButtonEvent::Clicked { .. } => true,
                                _ => false,
                            },
                            ButtonEventFilter::LongPress => match e {
                                ButtonEvent::LongPress { .. } => true,
                                _ => false,
                            },
                        },
                        _ => false,
                    },
                },
                Err(_) => false,
            },
        }
    }

    pub fn matches(&self, e: &Event) -> bool {
        match &self.strategy {
            EventFilterStrategy::Any => {
                self.entries.iter().any(|entry| Self::match_inner(entry, e))
            }
            EventFilterStrategy::All => {
                self.entries.iter().all(|entry| Self::match_inner(entry, e))
            }
        }
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, Ord, PartialOrd, PartialEq, Eq)]
pub enum EventFilterStrategy {
    Any,
    All,
}

#[derive(Serialize, Deserialize, Debug, Clone, Ord, PartialOrd, PartialEq, Eq)]
#[serde(tag = "type")]
pub enum EventFilterEntry {
    Any,
    Kind { kind: EventFilterKind },
}

#[derive(Serialize, Deserialize, Debug, Clone, Ord, PartialOrd, PartialEq, Eq)]
#[serde(tag = "type")]
pub enum EventFilterKind {
    Update,
    Button { filter: ButtonEventFilter },
}

#[derive(Serialize, Deserialize, Debug, Clone, Ord, PartialOrd, PartialEq, Eq)]
pub enum ButtonEventFilter {
    Down,
    Up,
    Clicked,
    LongPress,
}
